CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    account_no VARCHAR(50) NOT NULL UNIQUE,
    office_code VARCHAR(20),
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    old_password VARCHAR(255),
    role_id INT NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    email VARCHAR(150) NOT NULL UNIQUE,
    task_no VARCHAR(50),
    is_old_password BOOLEAN DEFAULT FALSE,
    question VARCHAR(255),
    answer VARCHAR(255),
    password_counter INT DEFAULT 0,
    last_password_date TIMESTAMP,
    created_by VARCHAR(100),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    updated_date TIMESTAMP,
    ip_address VARCHAR(50),
    password_reset_status BOOLEAN DEFAULT FALSE,
    term_and_condition TEXT,
    last_login TIMESTAMP,
    email_otp VARCHAR(10),
    mobile_otp VARCHAR(10),
    email_otp_created TIMESTAMP,
    mobile_otp_created TIMESTAMP,
    email_verified INT DEFAULT 0,
    mobile_verified INT DEFAULT 0,
    email_verified_at TIMESTAMP,
    mobile_verified_at TIMESTAMP,
    auth_data TEXT,
    otp VARCHAR(10),
    otp_created_at TIMESTAMP,
    task_questionno TIMESTAMP,
    forgot_otp VARCHAR(10),
    forgot_otp_created TIMESTAMP,
    auth_data_old TEXT,
    reset_otp VARCHAR(10),
    CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES roles(id)
);
