CREATE TABLE pdcao_messages (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Modern identity column
    message TEXT NOT NULL,                              -- Message content
    ip_address VARCHAR(50) NOT NULL,                           
    status VARCHAR(25) NOT NULL, -- Enforces allowed status values
    type VARCHAR(16) CHECK (type IN ('KEY_UPDATES', 'LATEST_UPDATES', 'TESTIMONIAL')) NOT NULL, -- Enforces allowed types
    flag BOOLEAN DEFAULT FALSE,                         -- Boolean flag with default `FALSE`
    created_by INT,                                     -- ID of the creator (foreign key potential)
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,   -- Record creation timestamp
    updated_by INT,                                     -- ID of the updater (foreign key potential)
    updated_date TIMESTAMP                              -- Timestamp of the last update
);
