export const saoCentralWing = [
 {
  id: 1,
  name: 'Smt. Shilpi Sahai',
  designation: 'SAO',
  section: 'Admin I, Admin II (Building), Security and CSD',
  phone_number: '26401136',
 },
 {
  id: 2,
  name: 'Uma Shankar Cherukuri',
  designation: 'SAO',
  section: 'PCDA Secretariat, Technical and Internal Audit',
  phone_number: '26401126',
 },
 {
  id: 3,
  name: 'Narendra',
  designation: 'SAO',
  section: 'Admin III (Admin./Pay)',
  phone_number: '',
 },
 {
  id: 4,
  name: 'Mohd Anwar Alam',
  designation: 'SAO',
  section: 'Pension Cell and SPARSH',
  phone_number: '26401115',
 },
 {
  id: 5,
  name: 'Anand Prakash',
  designation: 'SAO',
  section: 'PRO and Disbursement',
  phone_number: '26401355',
 },
 {
  id: 6,
  name: 'Sanjay Pandit',
  designation: 'SAO',
  section: 'N R Cell and Records',
  phone_number: '',
 },
 {
  id: 7,
  name: 'Sanjeev Kumar',
  designation: 'SAO',
  section: 'Legal Cell and RTI Cell',
  phone_number: '26401155',
 },
 {
  id: 8,
  name: 'S M Nagarkar',
  designation: 'SAO',
  section: 'FSR and Wet Canteen',
  phone_number: '26401222',
 },
 {
  id: 9,
  name: 'S Venkata Narasaiah',
  designation: 'SAO',
  section: 'PSC',
  phone_number: '26401140',
 },
 {
  id: 10,
  name: 'Shibabrata Paul',
  designation: 'SAO',
  section: 'PSC',
  phone_number: '26401140',
 },
 {
  id: 11,
  name: 'K Rajesh',
  designation: 'SAO',
  section: 'Accounts and Rent Cell',
  phone_number: '26401150',
 },
]

export const saoLedgerWing = [
 {
  id: 1,
  name: 'G Stalin Babu',
  designation: 'SAO',
  section: 'LW 19, FPC and LIC',
  phone_number: '26401219',
 },
 {
  id: 2,
  name: 'Arun Kumar Bhaskar',
  designation: 'SAO',
  section: 'LW SS Admin',
  phone_number: '26401240',
 },
 {
  id: 3,
  name: 'Smt. M Ramya',
  designation: 'SAO',
  section: 'LW SS Audit and IT Cell',
  phone_number: '26401234 / 26401220',
 },
 {
  id: 4,
  name: 'Sanjay Kumar Sinha',
  designation: 'SAO',
  section: 'LW 1',
  phone_number: '26401201',
 },
 {
  id: 5,
  name: 'Joyanta Kumar Ganguly',
  designation: 'SAO',
  section: 'LW 2',
  phone_number: '26401202',
 },
 {
  id: 6,
  name: 'Niraj Sinha',
  designation: 'SAO',
  section: 'LW 3',
  phone_number: '26401203',
 },
 {
  id: 7,
  name: 'Atul Kumar Srivastava',
  designation: 'SAO',
  section: 'LW 4',
  phone_number: '26401204',
 },
 {
  id: 8,
  name: 'Saurav Dutta',
  designation: 'SAO',
  section: 'LW 5',
  phone_number: '26401205',
 },
 {
  id: 9,
  name: 'Shankarsan Mishra',
  designation: 'SAO',
  section: 'LW 6',
  phone_number: '26401206',
 },
 {
  id: 10,
  name: 'Shahbaz Ahsan',
  designation: 'SAO',
  section: 'LW 7',
  phone_number: '26401207',
 },
 {
  id: 11,
  name: 'Bhagwan Rai',
  designation: 'SAO',
  section: 'LW 8',
  phone_number: '26401208',
 },
 {
  id: 12,
  name: 'Jay Prakash Upadhaya',
  designation: 'SAO',
  section: 'LW 9',
  phone_number: '26401209',
 },
 {
  id: 13,
  name: 'Rajesh Kumar Doley',
  designation: 'SAO',
  section: 'LW 10',
  phone_number: '26401210',
 },
 {
  id: 14,
  name: 'Sumit Kumar',
  designation: 'SAO',
  section: 'LW 11',
  phone_number: '26401219',
 },
 {
  id: 15,
  name: 'Amarnath Prasad',
  designation: 'SAO',
  section: 'LW 12',
  phone_number: '26401212',
 },
 {
  id: 16,
  name: 'Smt. G Shalini Srinivas',
  designation: 'SAO',
  section: 'LW 13',
  phone_number: '26401213',
 },
 {
  id: 17,
  name: 'Kumar Singh Chandra',
  designation: 'SAO',
  section: 'LW 14',
  phone_number: '26401214',
 },
 {
  id: 18,
  name: 'Ajay Kumar Mishra',
  designation: 'SAO',
  section: 'LW 15',
  phone_number: '26401215',
 },
 {
  id: 19,
  name: 'A Gifri',
  designation: 'SAO',
  section: 'LW 16',
  phone_number: '26401216',
 },
 {
  id: 20,
  name: 'Barnabas Gunaraj',
  designation: 'SAO',
  section: 'LW 17',
  phone_number: '26401217',
 },
 {
  id: 21,
  name: 'Jaideep Nag',
  designation: 'SAO',
  section: 'LW 18',
  phone_number: '26401201',
 },
]

export const saoTWing = [
 {
  id: 1,
  name: 'Sanjay Ramsinghani',
  designation: 'SAO',
  section: 'T 1 and T 2',
  phone_number: '26401301 & 26401302',
 },
 {
  id: 2,
  name: 'Ratnesh Kumar',
  designation: 'SAO',
  section: 'T 3 and T 4',
  phone_number: '26401303 & 26401304',
 },
 {
  id: 3,
  name: 'Sanjeev Kumar Dwivedi',
  designation: 'SAO',
  section: 'T 5 and T 6',
  phone_number: '26401305 & 26401306',
 },
 {
  id: 4,
  name: 'S R Deshpande',
  designation: 'SAO',
  section: 'T 7 and T 8',
  phone_number: '26401307 & 26401308',
 },
 {
  id: 5,
  name: 'Bimal Kumar',
  designation: 'SAO',
  section: 'T 9 and T 10',
  phone_number: '26401309 & 26401310',
 },
 {
  id: 6,
  name: 'Kaustubh K Jalgaonkar',
  designation: 'SAO',
  section: 'T 11 and TAPC',
  phone_number: '26401311',
 },
 {
  id: 7,
  name: 'Anurag Shekhar',
  designation: 'SAO',
  section: 'T SS (Additional charge of T Warrant)',
  phone_number: '26401360',
 },
]

export const saoEDPCentre = [
 {
  id: 1,
  name: 'J N Tulekar',
  designation: 'SAO',
  section: 'EDP and Website',
  phone_number: '26401145',
 },
 {
  id: 2,
  name: 'Manoj Kumar Pathak',
  designation: 'SAO',
  section: 'EDP and AFL',
  phone_number: '26401152',
 },
]
