export const RTIWingsOfficerData = [
 {
  id: '1',
  section: [
   'In-charge of all Sections (Except  EDP, Admin Estt., Admin Pay Section, Building Section and Security Section).',
   'Matters involving policy issues/ decisions/ matters and important   correspondence / reference to CGDA, HQrs. Office New Delhi will be submitted to PCDA.',
   'Group Training Manager(GTM)',
   'CPIO & RTI Cell',
   'Grievance Officer',
   'Vigilance Officer',
   'Chairman ROC/ JCM IV Steering Committee Meeting',
   'Chairman Welfare Committee',
   'President DARC',
  ],
  name_of_officer: 'Shri Chandra Prakash, Addl. CDA',
  phone_number: '26401103',
 },
 {
  id: '2',
  section: [
   'Ledger Wing 11 to 19 ',
   'Rent Cell',
   'Accounts Section',
   'NR Cell',
   'AFL',
  ],
  name_of_officer: 'Smt. Neela S Kumar, IDAS, DCDA',
  phone_number: '26401107',
 },
 {
  id: '3',
  section: [
   'Admin Section (AN-I)',
   'Building Section (AN-II)',
   'An/Pay Section (AN-III)',
   'Legal Cell',
   'CSD Canteen',
   'ISO',
  ],
  name_of_officer: 'Ms.  Seena Thomas, IDAS, DCDA',
  phone_number: '26401106',
 },
 {
  id: '4',
  section: [
   'Ledger Wing - 6 to 10',
   'Transportation Wing – 1 to 5',
   'Rajbhasha Anubhaga (OL)',
   'PRO',
   'Records Section',
  ],
  name_of_officer: 'Ms. Mamatha G, IDAS, ACDA',
  phone_number: '26401109',
 },
 {
  id: '5',
  section: [
   'IT Cell',
   'Accounts Wing',
   'Transport Wing 10 & 11',
   'T/SS, TAPC, T Course',
   'ISO Certificate re-validation',
   'Record Wing',
   'ACPIO',
   'Rent Cell',
   'PSC',
  ],
  name_of_officer: 'Shri Akashdeep P. Rai,\n' + 'IDAS, DCDA',
  phone_number: '26401139',
 },
 {
  id: '6',
  section: [
   'Ledger Wing – 01 to 05',
   'Transport Wing - 01 to 09',
   'T-Warrant',
   'Rajbhasha Anubhaag (OL)',
   'PRO',
  ],
  name_of_officer: 'Shri Alok Kumar Tiwari,\n' + 'IDAS, ACDA',
  phone_number: '26401139',
 },
]
