export const RTIWingsOfficerData = [
 {
  id: '1',
  section: [
   'In-charge of all Sections (Except  EDP, Admin Estt., Admin Pay Section, Building Section and Security Section).',
   'Matters involving policy issues/ decisions/ matters and important   correspondence / reference to CGDA, HQrs. Office New Delhi will be submitted to PCDA.',
   'Group Training Manager(GTM)',
   'CPIO & RTI Cell',
   'Grievance Officer',
   'Vigilance Officer',
   'Chairman ROC/ JCM IV Steering Committee Meeting',
   'Chairman Welfare Committee',
   'President DARC',
  ],
  name_of_officer: 'Shri Chandra Prakash,\n IDAS, Addl. CDA',
  phone_number: '26401103',
 },
 {
  id: '2',
  section: [
   'Ledger Wing 11 to 19 ',
   'Rent Cell',
   'Accounts Section',
   'NR Cell',
   'AFL',
  ],
  name_of_officer: 'Smt. Neela S Kumar,\n IDAS, DCDA',
  phone_number: '26401107',
 },
 {
  id: '3',
  section: [
   'Admin Section (AN-I)',
   'Building Section (AN-II)',
   'An/Pay Section (AN-III)',
   'Legal Cell',
   'CSD Canteen',
   'ISO',
  ],
  name_of_officer: 'Ms.  Seena Thomas,\n IDAS, DCDA',
  phone_number: '26401106',
 },
 {
  id: '4',
  section: [
   'Ledger Wing - 6 to 10',
   'Transportation Wing – 1 to 5',
   'Rajbhasha Anubhaga (OL)',
   'PRO',
   'Records Section',
  ],
  name_of_officer: 'Ms. Mamatha G,\n IDAS, ACDA',
  phone_number: '26401109',
 },
 {
  id: '5',
  section: [
   'EDP',
   'Ledger Wing- 1 to 5',
   'Transportation Wing 6 to 11',
   'DO II Cell',
   'Wet Canteen(6)',
   'PSC'
  ],
  name_of_officer: 'Ms. Shweta Pandey,\n IDAS, ACDA',
  phone_number: '26401110',
 },
 {
  id: '6',
  section: [
   'Ledger Wing SS (AT and Admin)',
   'Transportation Wing SS',
   'TAPC,  T Course & T Warrants',
   'SPARSH Centre & Pension Cell',
   'FSR',
   'ACPIO',
  ],
  name_of_officer: 'Shri U G Kadam, \n IDAS, ACDA',
  phone_number: '26401108',
 },
 {
    id: '7',
    section: [
     'Ledger Wing SS (AT)',
     'Technical Section & IA',
     'Section',
     'D Section',
     'FPC/LIC',
     'IT Cell',
    ],
    name_of_officer: 'Smt Leena Thankachan,\n  IDAS, ACDA',
    phone_number: '26401104',
   },
]
