import React from "react";
import { Checkbox } from "@/components/ui/checkbox";
import { cn } from "@/lib/utils"

function CalculatorCard({
  className,
  title,
  info_one,
  info_two,
  setIsCheckedDisclaimer,
  setOpenCalculator,
  isCheckedDisclaimer,
  openCalculator,
  children,
}) {
  return (
    <div className="flex gap-16">
      {openCalculator && isCheckedDisclaimer ? (
        <>{children}</>
      ) : (
        <div className="flex flex-col space-y-3">
          <h3
            className={cn(`text-2xl 2xl:text-3xl font-bold text-white p-2 text-justify`, className)}
          >
            {title}
          </h3>
          <div className="space-y-3  mb-11">
            <p className="text-justify">{info_one}</p>
            <hr />
            <p className="text-justify">{info_two}</p>
            <hr />

            <div className="flex gap-2">
              <Checkbox
                onCheckedChange={() =>
                  setIsCheckedDisclaimer((prevValue) => !prevValue)
                }
                className="my-1"
              />
              <div>
                <p className="text-justify">
                  <span className="font-bold">Disclaimer:</span>The result
                  generated by the above calculator developed by PCDA(O) is for
                  reference only. Any decisions made by the user concerned based
                  on the results given by the above calculator or the outcomes
                  thereof shall be the responsibility of the user Officer only,
                  and PCDA(O) or any employee serving under him shall not be
                  made liable for the same.
                </p>
              </div>
            </div>

            <hr />

            <p className="text-xl font-bold">
              Please tick the above check-box for proceeding ahead.
            </p>
          </div>

          <div className="w-full flex flex-row-reverse pt-10">
            <button
              className="w-fit rounded-full px-4 py-3 bg-statebluecolor text-white disabled:bg-gray-400 disabled:cursor-not-allowed"
              disabled={!isCheckedDisclaimer}
              onClick={() => setOpenCalculator((prevValue) => !prevValue)}
            >
              Open Pay Calculator
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

export default CalculatorCard;
